GET https://admin:Password1%2B@10.3.0.221:9200/


###
DELETE https://admin:Password1%2B@10.3.0.221:9200/_template/ingdiba_template

###
GET https://admin:Password1%2B@10.3.0.221:9200/_template/ingdiba_template

###
PUT https://admin:Password1%2B@10.3.0.221:9200/_template/ingdiba_template

{
  "template": "logstash-ingdiba*",
  "settings": {
    "number_of_shards": 2
  },
  "mappings": {
    "fluentd": {
      "_source": {
        "enabled": true
      },
      "properties": {
        "scBytes": {
          "type": "integer"
        },
        "csBytes": {
          "type": "integer"
        },
        "timeTaken": {
          "type": "integer"
        },
        "userAgent": {
          "type": "keyword"
        },
        "username": {
          "type": "keyword"
        },
        "uriQuery": {
          "type": "keyword"
        },
        "uriStem": {
          "type": "keyword"
        },
        "referer": {
          "type": "keyword"
        },
        "httpMethod": {
          "type": "keyword"
        },
        "httpStatus": {
          "type": "keyword"
        },
        "cookie": {
          "type": "text",
          "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
          }
        },
        "source": {
          "type": "keyword"
        },
        "ipAddress": {
          "type": "keyword"
        },
        "input_type": {
          "type": "keyword"
        },
        "beat.name": {
          "type": "keyword"
        },
        "beat.name": {
          "type": "keyword"
        },
        "beat.version": {
          "type": "keyword"
        },
        "beat.hostname": {
          "type": "keyword"
        },
        "@metadata.beat": {
          "type": "keyword"
        },
        "@metadata.type": {
          "type": "keyword"
        }        
      }
    }
  }
}


###
PUT https://admin:Password1%2B@10.3.0.221:9200/_template/operations_template

{
  "template": "logstash-operations*",
  "settings": {
    "number_of_shards": 2
  },
  "mappings": {
    "fluentd": {
      "_source": {
        "enabled": true
      },
      "properties": {
        "scBytes": {
          "type": "integer"
        },
        "csBytes": {
          "type": "integer"
        },
        "timeTaken": {
          "type": "integer"
        },
        "userAgent": {
          "type": "keyword"
        },
        "username": {
          "type": "keyword"
        },
        "uriQuery": {
          "type": "keyword"
        },
        "uriStem": {
          "type": "keyword"
        },
        "referer": {
          "type": "keyword"
        },
        "httpMethod": {
          "type": "keyword"
        },
        "httpStatus": {
          "type": "keyword"
        },
        "cookie": {
          "type": "text",
          "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
          }
        },
        "source": {
          "type": "keyword"
        },
        "ipAddress": {
          "type": "keyword"
        },
        "input_type": {
          "type": "keyword"
        },
        "beat.name": {
          "type": "keyword"
        },
        "beat.name": {
          "type": "keyword"
        },
        "beat.version": {
          "type": "keyword"
        },
        "beat.hostname": {
          "type": "keyword"
        },
        "@metadata.beat": {
          "type": "keyword"
        },
        "@metadata.type": {
          "type": "keyword"
        }        
      }
    }
  }
}

###

DELETE https://admin:Password1%2B@10.3.0.221:9200/logstash-operations*

### 

GET https://admin:Password1%2B@10.3.0.221:9200/_cat/indices

###

GET https://admin:Password1%2B@10.3.0.221:9200/logstash-ingdiba-2017.05.11/_mappings

###

GET http://10.9.80.19:9200/_template/logstash_template

PUT /_template/logstash_template
{
  "template": "logstash-*",
  "mappings":{
     "logstash": {
      "properties": {
        "host.keyword": {
          "type": "keyword"
        }
      }
    }
  }
}